{
 "title": "Puppet server Developer Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  { "title": "Cpu and jrubies", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Heap Memory usage",
   "type": "graph",
   "description": "Dispalys the heap memory usage",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "bits" }
   ],
   "targets": [
    {
     "expr": "puppet_master_memory_guage{is_heap=\"true\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Non Heap Memory usage",
   "type": "graph",
   "description": "Dispalys the Non heap memory usage",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "bits" }
   ],
   "targets": [
    {
     "expr": "puppet_master_memory_guage{is_heap=\"false\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Cpu usage",
   "type": "graph",
   "description": "displays the gc and cpu usage",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "puppet_master_jvm_guage{metric=\"cpu_usage\"}",
     "legendFormat": "CPU usage"
    },
    {
     "expr": "puppet_master_jvm_guage{metric=\"gc_cpu_usage\"}",
     "legendFormat": "GC CPU usage"
    }
   ]
  },
  {
   "title": "Free jrubies",
   "type": "graph",
   "description": "Displays the total, average and current free jrubies",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "puppet_master_jruby_guage{name=~\".*jrubies\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Requests count",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "puppet_master_http_guage{type=\"count\"}",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "Requests Mean",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 18 },
   "targets": [
    {
     "expr": "puppet_master_http_guage{type=\"mean\"}",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "Requests Aggregate",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 18 },
   "targets": [
    {
     "expr": "puppet_master_http_guage{type=\"aggregate\"}",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "Functions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "Functions Count",
     "type": "table",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 3 },
     "targets": [
      {
       "expr": "puppet_master_profiler_function_guage{type=\"count\"}",
       "legendFormat": "{{route}}"
      }
     ]
    },
    {
     "title": "Functions Mean",
     "type": "table",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 3 },
     "targets": [
      {
       "expr": "puppet_master_profiler_function_guage{type=\"mean\"}"
      }
     ]
    },
    {
     "title": "Functions Aggreagate",
     "type": "table",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 3 },
     "targets": [
      {
       "expr": "puppet_master_profiler_function_guage{type=\"aggregate\"}"
      }
     ]
    }
   ]
  },
  { "title": "Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Resources Count",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "puppet_master_profiler_resource_guage{type=\"count\"}",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "Resource Mean",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 28 },
   "targets": [
    {
     "expr": "puppet_master_profiler_resource_guage{type=\"mean\"}"
    }
   ]
  },
  {
   "title": "Resource Aggreagate",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 28 },
   "targets": [
    {
     "expr": "puppet_master_profiler_resource_guage{type=\"aggregate\"}"
    }
   ]
  },
  {
   "title": "Catalog",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "collapsed": true
  },
  {
   "title": "Catalog Count",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 37 },
   "targets": [
    {
     "expr": "puppet_master_profiler_catalog_guage{type=\"count\"}",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "Catalog Mean",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 37 },
   "targets": [
    {
     "expr": "puppet_master_profiler_catalog_guage{type=\"mean\"}"
    }
   ]
  },
  {
   "title": "Catalog Aggreagate",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 37 },
   "targets": [
    {
     "expr": "puppet_master_profiler_catalog_guage{type=\"aggregate\"}"
    }
   ]
  }
 ]
}