{
 "title": "samplemaster",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Thread count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "puppet_master_thread_guage",
     "legendFormat": "{{name}}",
     "target": "alias(puppetlabs.master.example.com.num-cpus,'num cpus')"
    }
   ]
  },
  {
   "title": "Request Durations",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "puppet_master_http_guage{route=\"puppet-v3-catalog-/*/\", type=\"mean\"}",
     "legendFormat": "{{route}}",
     "target": "alias(puppetlabs.master.example.com.http.puppet-v3-catalog-.*.-requests.mean,'catalog')"
    },
    {
     "expr": "puppet_master_http_guage{route=\"puppet-v3-report-/*/\", type=\"mean\"}",
     "legendFormat": "{{route}}",
     "target": "alias(puppetlabs.master.example.com.http.puppet-v3-report-.*.-requests.mean,'report')"
    },
    {
     "expr": "puppet_master_http_guage{route=\"puppet-v3-file_metadatas-/*/\", type=\"mean\"}",
     "legendFormat": "{{route}}",
     "target": "alias(puppetlabs.master.example.com.http.puppet-v3-node-.*.-requests.mean,'node')"
    },
    {
     "expr": "puppet_master_http_guage{route=\"puppet-v3-file_metadata-/*/\", type=\"mean\"}",
     "legendFormat": "{{route}}",
     "target": "alias(puppetlabs.master.example.com.http.puppet-v3-file_metadatas-.*.-requests.mean,'file_metadatas')"
    },
    {
     "expr": "puppet_master_http_guage{route=\"puppet-v3-file_content-/*/\", type=\"mean\"}",
     "legendFormat": "{{route}}",
     "target": "alias(puppetlabs.master.example.com.http.puppet-v3-file_metadata-.*.-requests.mean,'file_metadata')"
    },
    {
     "expr": "puppet_master_http_guage{route=\"other\", type=\"mean\"}",
     "legendFormat": "{{route}}",
     "target": "alias(puppetlabs.master.example.com.http.puppet-v3-file_content-.*.-requests.mean,'file_content')"
    },
    {
     "expr": "puppet_master_http_guage{route=\"total\", type=\"mean\"}",
     "legendFormat": "{{route}}",
     "target": "alias(puppetlabs.master.example.com.http.other-requests.mean,'other')"
    },
    {
     "expr": "puppet_master_http_guage{route=\"puppet-v3-node-/*/\", type=\"mean\"}"
    }
   ]
  },
  {
   "title": "Request Ratios",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "percentunit", "label": "Percentage of Requests" }
   ],
   "targets": [
    {
     "expr": "puppet_master_http_guage{route=\"puppet-v3-file_metadatas-/*/\", type=\"count\"}  / ignoring(route) puppet_master_http_guage{route=\"total\", type=\"count\"}",
     "legendFormat": "File_metadatas",
     "target": "alias(scale(puppetlabs.master.example.com.http.puppet-v3-catalog-.*.-percentage,100),'catalog')"
    },
    {
     "expr": "puppet_master_http_guage{route=\"puppet-v3-file_metadata-/*/\", type=\"count\"}  / ignoring(route) puppet_master_http_guage{route=\"total\", type=\"count\"}",
     "legendFormat": "File_metadata",
     "target": "alias(scale(puppetlabs.master.example.com.http.puppet-v3-report-.*.-percentage,100),'report')"
    },
    {
     "expr": "puppet_master_http_guage{route=\"puppet-v3-file_content-/*/\", type=\"count\"}  / ignoring(route) puppet_master_http_guage{route=\"total\", type=\"count\"}",
     "legendFormat": "File_content",
     "target": "alias(scale(puppetlabs.master.example.com.http.puppet-v3-node-.*.-percentage,100),'node')"
    },
    {
     "expr": "puppet_master_http_guage{route=\"puppet-v3-catalog-/*/\", type=\"count\"}  / ignoring(route) puppet_master_http_guage{route=\"total\", type=\"count\"}",
     "legendFormat": "Catalog",
     "target": "alias(scale(puppetlabs.master.example.com.http.puppet-v3-file_metadatas-.*.-percentage,100),'file_metadatas')"
    },
    {
     "expr": "puppet_master_http_guage{route=\"puppet-v3-report-/*/\", type=\"count\"}  / ignoring(route) puppet_master_http_guage{route=\"total\", type=\"count\"}",
     "legendFormat": "Report",
     "target": "alias(scale(puppetlabs.master.example.com.http.puppet-v3-file_metadata-.*.-percentage,100),'file_metadata')"
    },
    {
     "expr": "puppet_master_http_guage{route=\"puppet-v3-node-/*/\", type=\"count\"}  / ignoring(route) puppet_master_http_guage{route=\"total\", type=\"count\"}",
     "legendFormat": "Node",
     "target": "alias(scale(puppetlabs.master.example.com.http.puppet-v3-file_content-.*.-percentage,100),'file_content')"
    }
   ]
  },
  {
   "title": "Compilation",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "puppet_master_profiler_catalog_guage{metric=\"compile\", type=\"mean\"}",
     "legendFormat": "{{metric}}",
     "target": "alias(puppetlabs.master.example.com.compiler.compile.mean,'compile')"
    },
    {
     "expr": "puppet_master_profiler_catalog_guage{metric=\"find_node\", type=\"mean\"}",
     "legendFormat": "{{metric}}",
     "target": "alias(puppetlabs.master.example.com.functions.mean,'function calls')"
    },
    {
     "target": "alias(puppetlabs.master.example.com.compiler.find_node.mean,'find_node')"
    },
    {
     "legendFormat": "{{metric}}",
     "target": "alias(puppetlabs.master.example.com.compiler.static_compile.mean,'static compile')"
    },
    {
     "target": "alias(puppetlabs.master.example.com.compiler.static_compile_postprocessing.mean,'static compile postprocessing')"
    },
    {
     "target": "alias(puppetlabs.master.example.com.compiler.find_facts.mean,'find_facts')"
    }
   ]
  },
  {
   "title": "Communications with PuppetDB",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "puppet_master_profiler_puppetdb_guage{ type=\"mean\"}",
     "legendFormat": "{{metric}}",
     "target": "alias(puppetlabs.master.example.com.puppetdb.catalog.save.mean,'catalog save')"
    }
   ]
  },
  {
   "title": "File descriptor",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "puppet_master_file_guage",
     "legendFormat": "{{name}}",
     "target": "alias(puppetlabs.master.example.com.file-sync-storage.commit-timer.mean,'commit')"
    }
   ]
  },
  {
   "title": "JRubies",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "puppet_master_jruby_guage{name=~\".*jrubies\"}",
     "legendFormat": "{{name}}",
     "target": "alias(puppetlabs.master.example.com.jruby.num-jrubies,'num jrubies')"
    }
   ]
  },
  {
   "title": "JRuby Timers",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 16 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "puppet_master_jruby_guage{name=~\".*time\"}",
     "legendFormat": "{{name}}",
     "target": "alias(puppetlabs.master.example.com.jruby.borrow-timer.mean,'borrow time')"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 16 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "puppet_master_memory_guage{is_heap=\"true\"}",
     "legendFormat": "heap-{{type}}",
     "target": "alias(puppetlabs.master.example.com.memory.heap.used,'heap used')"
    },
    {
     "expr": "puppet_master_memory_guage{is_heap=\"false\"}",
     "legendFormat": "Non-heap-{{type}}",
     "target": "alias(puppetlabs.master.example.com.memory.non-heap.used,'non-heap used')"
    }
   ]
  }
 ]
}