{
 "title": "Puppet Report",
 "description": "Detailed information about Puppet report metrics",
 "tags": [ "Puppet" ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "Host",
    "query": "label_values(puppetdb_status_node_guage, node)"
   },
   {
    "name": "environment",
    "label": "Environment",
    "query": "label_values(puppetdb_status_node_guage, puppet_environment)"
   }
  ]
 },
 "panels": [
  { "title": "Last Puppet Report", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Time since last report",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "puppetdb_last_report_time_node_guage{node=\"$host\", puppet_environment=\"$environment\"}"
    }
   ]
  },
  {
   "title": "Total of Events",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "puppetdb_report_event_node_guage{node=\"$host\", puppet_environment=\"$environment\", name=\"total\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Failure",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "puppetdb_report_event_node_guage{node=\"$host\", puppet_environment=\"$environment\", name=\"failure\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Successful",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "current"
  },
  {
   "title": "Resources",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "puppetdb_report_resources_node_guage{name=\"total\",node=\"$host\",puppet_environment=\"$environment\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Changes",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "format": "none",
   "valueName": "avg"
  },
  { "title": "New row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Duration (latest report)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "topk(15,puppetdb_report_time_node_guage{node=\"$host\",puppet_environment=\"$environment\"} > - 1)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Resources by status (latest report)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "puppetdb_report_resources_node_guage{node=\"$host\", puppet_environment=\"$environment\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Puppet Reports over time", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Duration (over time)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "puppetdb_report_time_node_guage{name=~\"config_retrieval|total\",node=\"$host\", puppet_environment=\"$environment\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Resources by status (over time)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "puppetdb_report_time_node_guage{node=\"$host\",puppet_environment=\"$environment\"} > -1",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}